package agent
import("log";"net";"sync";"time";"github.com/google/gopacket";"github.com/google/gopacket/layers";"github.com/google/gopacket/pcap")
type packetCapture struct{mu sync.Mutex;seconds map[int64]*packetBucket}
type packetBucket struct{packets,bytes,syn,udp,icmp,tcp uint64;sources map[string]struct{}}
func newPacketCapture()*packetCapture{return &packetCapture{seconds:make(map[int64]*packetBucket)}}
func(p *packetCapture)start(logger *log.Logger){ifs,e:=net.Interfaces();if e!=nil{logger.Printf("interfaces: %v",e);return};for _,i:=range ifs{if i.Flags&net.FlagUp==0||i.Flags&net.FlagLoopback!=0{continue};go p.captureInterface(i.Name,logger)}}
func(p *packetCapture)captureInterface(name string,logger *log.Logger){h,e:=pcap.OpenLive(name,128,true,pcap.BlockForever);if e!=nil{logger.Printf("pcap %s: %v",name,e);return};defer h.Close();_=h.SetBPFFilter("ip or ip6");for packet:=range gopacket.NewPacketSource(h,h.LinkType()).Packets(){p.observe(packet)}}
func(p *packetCapture)observe(packet gopacket.Packet){now:=time.Now().Unix();p.mu.Lock();defer p.mu.Unlock();b:=p.seconds[now];if b==nil{b=&packetBucket{sources:map[string]struct{}{}};p.seconds[now]=b};b.packets++;b.bytes+=uint64(len(packet.Data()));var src string;if x:=packet.Layer(layers.LayerTypeIPv4);x!=nil{src=x.(*layers.IPv4).SrcIP.String()}else if x:=packet.Layer(layers.LayerTypeIPv6);x!=nil{src=x.(*layers.IPv6).SrcIP.String()};if src!=""{b.sources[src]=struct{}{}};if x:=packet.Layer(layers.LayerTypeTCP);x!=nil{b.tcp++;if x.(*layers.TCP).SYN{b.syn++}};if packet.Layer(layers.LayerTypeUDP)!=nil{b.udp++};if packet.Layer(layers.LayerTypeICMPv4)!=nil||packet.Layer(layers.LayerTypeICMPv6)!=nil{b.icmp++}}
func(p *packetCapture)stats()PacketStats{p.mu.Lock();defer p.mu.Unlock();now:=time.Now().Unix();var b packetBucket;b.sources=map[string]struct{}{};for ts,x:=range p.seconds{if ts>=now-9{b.packets+=x.packets;b.bytes+=x.bytes;b.syn+=x.syn;b.udp+=x.udp;b.icmp+=x.icmp;b.tcp+=x.tcp;for s:=range x.sources{b.sources[s]=struct{}{}}};if ts<now-12{delete(p.seconds,ts)}};return PacketStats{PacketsPerSecond:float64(b.packets)/10,BitsPerSecond:float64(b.bytes*8)/10,SynPerSecond:float64(b.syn)/10,UdpPerSecond:float64(b.udp)/10,IcmpPerSecond:float64(b.icmp)/10,UniqueSources:len(b.sources),TcpPackets:b.tcp,UdpPackets:b.udp,IcmpPackets:b.icmp}}
func interfaceAddresses(i net.Interface)[]string{var out []string;a,_:=i.Addrs();for _,x:=range a{for _,part:=range []string{x.String()}{if n:=len(part);n>0{for j,c:=range part{if c=='/'{out=append(out,part[:j]);break}}}}};return out}
